server:
  port: 8082
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  application:
    name: Feign0001

eureka:
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 1000


#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://192.168.0.82:8761/eureka/
#    fetch-registry: true
